[tox]
skipsdist = True

[testenv:linters]
skipsdist = True
deps =
  pre-commit
commands =
  pre-commit run --all-files --show-diff-on-failure

[testenv:py{3,310,311,312,313}]
deps =
  -r {toxinidir}/test-requirements.txt
commands =
  pytest --cov-report term-missing --cov-report html --cov=plugins/ tests/unit/

[testenv:molecule-venv]
deps =
  -r {toxinidir}/test-requirements.txt
commands =
  molecule {posargs}

[testenv:molecule-aio]
deps =
  {[testenv:molecule-venv]deps}
passenv =
  KUBERNETES_VERSION
commands =
  molecule test -s aio

[testenv:molecule-bgp]
deps =
  {[testenv:molecule-venv]deps}
passenv =
  KUBERNETES_VERSION
commands =
  molecule test -s bgp

[testenv:molecule-cluster-api]
deps =
  {[testenv:molecule-venv]deps}
commands =
  molecule test -s cluster-api
passenv =
  KUBERNETES_VERSION
  CLUSTER_API_VERSION
  CLUSTER_API_INFRA_VERSION
  CLUSTER_API_OPENSTACK_CONTROLLER
  MOLECULE_DISTRO

[testenv:molecule-cluster-api-upgrade]
deps =
  {[testenv:molecule-venv]deps}
commands =
  molecule test -s cluster-api-upgrade

[testenv:molecule-cluster-upgrade]
deps =
  {[testenv:molecule-venv]deps}
commands =
  molecule test -s cluster-upgrade
passenv =
  KUBERNETES_VERSION
  OLD_KUBERNETES_VERSION

[testenv:molecule-ha]
deps =
  {[testenv:molecule-venv]deps}
passenv =
  KUBERNETES_VERSION
  MOLECULE_DISTRO
commands =
  molecule test -s ha

[testenv:molecule-helm]
deps =
  {[testenv:molecule-venv]deps}
commands =
  molecule test -s helm

[testenv:molecule-upload-helm-chart]
deps =
  {[testenv:molecule-venv]deps}
commands =
  molecule test -s upload-helm-chart
