[tox]
skipsdist = True

[testenv:linters]
skipsdist = True
deps =
  -r {toxinidir}/test-requirements.txt
commands =
  flake8
  ansible-lint

[testenv:ansible-test]
deps =
  -r {toxinidir}/test-requirements.txt

allowlist_externals =
  rm

setenv =
  ANSIBLE_COLLECTIONS_PATH=/tmp/ansible-test
  ANSIBLE_TEST_CONTENT_ROOT=/tmp/ansible-test/ansible_collections/adriacloud/kubernetes

commands_pre =
  ansible-galaxy collection install --collections-path /tmp/ansible-test .

commands =
  ansible-test units --python-interpreter {envbindir}/python3 --coverage

commands_post =
  ansible-test coverage report
  rm -rf /tmp/ansible-test

[testenv:molecule-venv]
deps =
  -r {toxinidir}/test-requirements.txt
commands =
  molecule {posargs}

[testenv:molecule-aio]
deps =
  {[testenv:molecule-venv]deps}
passenv =
  KUBERNETES_VERSION
commands =
  molecule test -s aio

[testenv:molecule-artifacts]
deps =
  {[testenv:molecule-venv]deps}
commands =
  molecule test -s download_artifacts

[testenv:molecule-bgp]
deps =
  {[testenv:molecule-venv]deps}
passenv =
  KUBERNETES_VERSION
commands =
  molecule test -s bgp

[testenv:molecule-cluster-api]
deps =
  {[testenv:molecule-venv]deps}
commands =
  molecule test -s cluster-api
passenv =
  KUBERNETES_VERSION
  CLUSTER_API_VERSION
  CLUSTER_API_INFRA_VERSION
  CLUSTER_API_OPENSTACK_CONTROLLER
  MOLECULE_DISTRO

[testenv:molecule-cluster-api-upgrade]
deps =
  {[testenv:molecule-venv]deps}
commands =
  molecule test -s cluster-api-upgrade

[testenv:molecule-cluster-upgrade]
deps =
  {[testenv:molecule-venv]deps}
commands =
  molecule test -s cluster-upgrade
passenv =
  KUBERNETES_VERSION
  OLD_KUBERNETES_VERSION

[testenv:molecule-ha]
deps =
  {[testenv:molecule-venv]deps}
passenv =
  KUBERNETES_VERSION
  MOLECULE_DISTRO
commands =
  molecule test -s ha

[testenv:molecule-helm]
deps =
  {[testenv:molecule-venv]deps}
commands =
  molecule test -s helm

[testenv:molecule-upload-helm-chart]
deps =
  {[testenv:molecule-venv]deps}
commands =
  molecule test -s upload-helm-chart
