# Copyright (c) 2023 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

kubelet_download_url: >-
  https://dl.k8s.io/release/v{{ kubelet_version }}/bin/{{ ansible_facts['system'] | lower }}/{{ defaults_goarch }}/kubelet
kubelet_download_dest: /usr/bin/kubelet
kubelet_binary_checksum: "sha256:{{ kubelet_download_url }}.sha256"

# Allow usage of swap memory for the Kubelet
# WARNING: Do not enable this unless you know what you are doing.
kubelet_allow_unsafe_swap: false

# List of packages to be installed as dependencies
kubelet_packages: "{{ _kubelet_dependencies + _kubelet_cni_dependencies }}"
kubelet_packages_state: "{{ package_state | default('present') }}"

# List of sysctl parameters to set
kubelet_sysctls:
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1
  - name: net.ipv4.conf.all.rp_filter
    value: 0
  - name: fs.inotify.max_queued_events
    value: 1048576
  - name: fs.inotify.max_user_instances
    value: 8192
  - name: fs.inotify.max_user_watches
    value: 1048576
  - name: net.ipv6.conf.all.disable_ipv6
    value: 0
    set: true

# CRI related variables
kubelet_cri_socket: "{{ defaults_containerd_socket | default('/run/containerd/containerd.sock') }}"
kubelet_crictl_version: 1.35.0
kubelet_crictl_url: >-
  https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ kubelet_crictl_version
    }}/crictl-v{{ kubelet_crictl_version }}-linux-{{ defaults_goarch }}.tar.gz
kubelet_crictl_checksum: "sha256:{{ kubelet_crictl_url }}.sha256"
kubelet_crictl_dest: "/var/lib/downloads/crictl-v{{ kubelet_crictl_version }}-linux-{{ defaults_goarch }}.tar.gz"

# CNI related variables
kubelet_cni_plugins_version: 1.9.1
kubelet_cni_plugins_url: >-
  https://github.com/containernetworking/plugins/releases/download/v{{ kubelet_cni_plugins_version
    }}/cni-plugins-linux-{{ defaults_goarch }}-v{{ kubelet_cni_plugins_version }}.tgz
kubelet_cni_plugins_checksum: "sha256:{{ kubelet_cni_plugins_url }}.sha256"
kubelet_cni_plugins_archive_dest: "/var/lib/downloads/cni-plugins-linux-{{ defaults_goarch }}-v{{ kubelet_cni_plugins_version }}.tgz"
kubelet_cni_kernel_modules:
  - br_netfilter
  - ip_tables
  - ip6_tables
  - nf_conntrack

# Node IP address
kubelet_node_ip: "{{ ansible_facts['default_ipv4'].address }}"

# Kubelet hostname
kubelet_hostname: "{{ inventory_hostname_short }}"
