# Copyright (c) 2023 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

galaxy_info:
  author: VEXXHOST, Inc.
  description: Ansible role for "binary_download"
  license: Apache-2.0
  min_ansible_version: 5.5.0
  standalone: false
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal

dependencies:
  - role: tar
  - role: directory
    vars:
      directory_path: "{{ download_artifact_work_directory }}"
  - role: directory
    vars:
      directory_path: "{{ download_artifact_dest | dirname }}"
      directory_owner: "{{ download_artifact_owner | default(omit) }}"
      directory_recurse: true
  - role: directory
    when: download_artifact_unarchive
    vars:
      directory_path: "{{ download_artifact_unarchive_dest }}"
      directory_mode: "0755"
      directory_recurse: true
