# Copyright (c) 2023 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

helm_version: v4.2.0

helm_download_url: "https://get.helm.sh/helm-{{ helm_version }}-{{ ansible_facts['system'] | lower }}-{{ defaults_goarch }}.tar.gz"
helm_download_dest: "/var/lib/downloads/helm-{{ helm_version }}-{{ ansible_facts['system'] | lower }}-{{ defaults_goarch }}.tar.gz"
helm_binary_checksum: "sha256:{{ helm_download_url }}.sha256"

helm_diff_version: v3.15.7
helm_diff_checksums:
  amd64:
    v3.8.1: f78867edfde60e2506e3228f706beaf96d1ae3ee5f169f42315acbd513794078
    v3.15.2: e7b5cdea15df6365f74be37dcb2a3c4a7537a71dc4c3f9b5b871b7c4b07309f5
    v3.15.7: ff7b1b6f3f4fafeac1d0e2c0c82eafac6fa7601bda52396355bf931ecf3a304a
  arm64:
    v3.8.1: d451e4772a3987710f485de4caed760583c88f8f15864a623b3fbd73be7077ec
    v3.15.2: 077477871be96a866fb2ef777fd1cb2c66e6b3768bd5139672c567e2d0038b04
    v3.15.7: 2ec1e1078b8984ca04221ab110f662b6da5db29b5246f43f86d533eea3875e4d

helm_diff_download_url: >-
  https://github.com/databus23/helm-diff/releases/download/{{ helm_diff_version }}/helm-diff-{{ ansible_facts['system'] | lower }}-{{ defaults_goarch }}.tgz
helm_diff_download_dest: "/var/lib/downloads/helm-diff-{{ ansible_facts['system'] | lower }}-{{ defaults_goarch }}.tgz"
helm_diff_checksum: "{{ helm_diff_checksums[defaults_goarch][helm_diff_version] }}"
