name: Publish to Ansible Galaxy

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Collection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: "test-requirements.txt"

      - name: Install ansible-core
        run: pip install ansible-core

      - name: Build Ansible Collection
        run: ansible-galaxy collection build

      - name: Publish Ansible Collection to Galaxy
        env:
          ANSIBLE_GALAXY_TOKEN: ${{ secrets.GALAXY_API_KEY }}
        run: ansible-galaxy collection publish *.tar.gz --api-key $ANSIBLE_GALAXY_TOKEN
